Jose related products carrusel
Farmacia-Logistica/jludwing-prixz-custom-related-products- pull request #10
Opened 2024-08-12 22:38 UTC by JoseCcariQ

2024-08-12 23:01 UTC, jludwing approved these changes
Excelentes mejoras.

2024-08-13 00:03 UTC, FernandoHdzEsp approved these changes

2024-08-23 03:21 UTC, mxnu requested changes

2024-08-23 03:21 UTC, mxnu commented on prixz-custom-related-products.php
> +        echo 'Invalid API response';
Eliminar echo

2024-08-23 03:21 UTC, mxnu commented on prixz-custom-related-products.php
> +        echo 'Error: ' . $response->get_error_message();
Eliminar echo

2024-08-23 03:27 UTC, JoseCcariQ commented on prixz-custom-related-products.php
> +        echo 'Invalid API response';
eliminado

2024-08-23 03:27 UTC, JoseCcariQ commented on prixz-custom-related-products.php
> +        echo 'Error: ' . $response->get_error_message();
eliminado

2024-08-23 03:28 UTC, mxnu approved these changes
Ok

2024-08-23 03:28 UTC, JoelNieto90 approved these changes

2024-08-23 03:28 UTC, merged